# Generated by Django 3.2.16 on 2022-12-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=10, verbose_name='用户名')),
                ('uage', models.IntegerField(null=True, verbose_name='年龄')),
                ('umobile', models.CharField(max_length=11, null=True, verbose_name='手机号')),
                ('uos', models.IntegerField(choices=[(0, 'linux'), (1, 'win')], default=0, verbose_name='系统')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'tb_bbsuser',
            },
        ),
        migrations.CreateModel(
            name='BBSPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=200, verbose_name='帖子名字')),
                ('bdate', models.DateField(verbose_name='发帖时间')),
                ('bclick', models.IntegerField(default=0, verbose_name='点击次数')),
                ('bcomment', models.IntegerField(default=0, verbose_name='回复次数')),
                ('burl', models.CharField(default=0, max_length=100, verbose_name='链接')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('b_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mavlink_serial_http_adaptor.users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'db_table': 'tb_bbsposts',
            },
        ),
    ]
